const properties = [
    {
        id: 1,
        title: "Modern Condo in Makati",
        type: "condo",
        price: 25000,
        bedrooms: 2,
        bathrooms: 2,
        area: 75,
        location: "Makati City, Metro Manila",
        lat: 14.5547,
        lng: 121.0244,
        available: true,
        image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Swimming Pool", "Gym", "24/7 Security", "Parking"],
        description: "A modern 2-bedroom condo in the heart of Makati with great amenities."
    },
    {
        id: 2,
        title: "Cozy Townhouse in Quezon City",
        type: "townhouse",
        price: 15000,
        bedrooms: 3,
        bathrooms: 2,
        area: 120,
        location: "Quezon City, Metro Manila",
        lat: 14.6760,
        lng: 121.0437,
        available: true,
        image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Garden", "Parking", "Near Schools", "Quiet Neighborhood"],
        description: "Spacious townhouse perfect for families in a quiet Quezon City neighborhood."
    },
    {
        id: 3,
        title: "Beachfront House in Boracay",
        type: "house",
        price: 35000,
        bedrooms: 4,
        bathrooms: 3,
        area: 200,
        location: "Boracay, Aklan",
        lat: 11.9674,
        lng: 121.9248,
        available: false,
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Beach Access", "Private Pool", "Ocean View", "Fully Furnished"],
        description: "Luxury beachfront villa with stunning views in Boracay."
    },
    {
        id: 4,
        title: "Affordable Apartment in Cebu",
        type: "apartment",
        price: 8000,
        bedrooms: 1,
        bathrooms: 1,
        area: 40,
        location: "Cebu City, Cebu",
        lat: 10.3157,
        lng: 123.8854,
        available: true,
        image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Near University", "Public Transport", "Affordable", "Laundry Area"],
        description: "Budget-friendly apartment perfect for students in Cebu City."
    },
    {
        id: 5,
        title: "Luxury Penthouse in BGC",
        type: "condo",
        price: 80000,
        bedrooms: 3,
        bathrooms: 3,
        area: 180,
        location: "Taguig City, Metro Manila",
        lat: 14.5534,
        lng: 121.0511,
        available: true,
        image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["City View", "Rooftop Pool", "Smart Home", "Concierge"],
        description: "Ultra-modern penthouse with panoramic views of Manila."
    },
    {
        id: 6,
        title: "Traditional House in Vigan",
        type: "house",
        price: 12000,
        bedrooms: 2,
        bathrooms: 1,
        area: 90,
        location: "Vigan City, Ilocos Sur",
        lat: 17.5745,
        lng: 120.3869,
        available: true,
        image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Heritage Style", "Near Tourist Spots", "Garden", "Quiet Area"],
        description: "Charming traditional house in the historic city of Vigan."
    },
    {
        id: 7,
        title: "Studio Apartment in Davao",
        type: "apartment",
        price: 6000,
        bedrooms: 1,
        bathrooms: 1,
        area: 30,
        location: "Davao City, Davao del Sur",
        lat: 7.1907,
        lng: 125.4553,
        available: false,
        image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Fully Furnished", "24/7 Security", "Near Market", "Affordable"],
        description: "Compact and fully furnished studio apartment in central Davao."
    },
    {
        id: 8,
        title: "Family House in Subic",
        type: "house",
        price: 18000,
        bedrooms: 4,
        bathrooms: 2,
        area: 150,
        location: "Subic, Zambales",
        lat: 14.7942,
        lng: 120.2837,
        available: true,
        image: "https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
        features: ["Large Garden", "Parking for 2 Cars", "Near Beach", "Quiet Neighborhood"],
        description: "Spacious family home in the peaceful area of Subic."
    }
];